choco install firefox -y
choco install googlechrome -y
choco install adobereader -y
choco install zoom -y
choco install python3 -y
choco install python -y
choco install vlc -y
choco install 7zip -y
choco install notepadplusplus -y
choco install git -y
choco install paint.net -y
choco install winrar -y
choco install ccleaner -y
choco install vscode -y
choco install autohotkey.portable -y
choco install wget -y
choco install filezilla -y
choco install slack -y
choco install nodejs -y
choco install curl -y
choco install gimp -y
choco install dropbox -y
choco install thunderbird -y
choco install spotify -y
choco install jq -y
choco install putty -y
choco install itunes -y
choco install vim -y
choco install winscp -y
choco install wireshark -y
choco install onedrive -y
choco install brave -y
choco install cygwin -y
choco install virtualbox -y
choco install webex-meetings -y
choco install windirstat -y
choco install audacity -y
choco install ffmpeg -y
choco install docker-desktop -y
choco install gradle -y
choco install maven -y
choco install signal -y
choco install qbittorrent -y
choco install openjdk -y
choco install bitwarden -y
choco install rufus -y
choco install chocolatey-core.extension -y
choco install git.install -y
choco install googledrive -y
choco install malwarebytes -y
choco install obs-studio -y
choco install streamlabs-obs -y
choco install steam -y
choco install minecraft-launcher -y
choco install tabby -y
choco install alacritty -y
choco install cyberduck -y
choco install intellijidea-community -y
choco install pycharm-community -y
