Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
choco source remove -n=chocolatey
choco source add -n=nexus -s=http://192.168.1.152:8081/repository/chocolatey-group/

choco install firefox
choco install googlechrome
choco install adobereader
choco install zoom
choco install python3
choco install python
choco install vlc
choco install 7zip
choco install notepadplusplus
choco install git
choco install paint.net
choco install winrar
choco install ccleaner
choco install vscode
choco install autohotkey.portable
choco install wget
choco install filezilla
choco install slack
choco install nodejs
choco install curl
choco install gimp
choco install dropbox
choco install thunderbird
choco install spotify
choco install jq
choco install putty
choco install itunes
choco install vim
choco install winscp
choco install wireshark
choco install onedrive
choco install brave
choco install cygwin
choco install virtualbox
choco install webex-meetings
choco install windirstat
choco install audacity
choco install ffmpeg
choco install docker-desktop
choco install gradle
choco install maven
choco install signal
choco install qbittorrent
choco install openjdk
choco install bitwarden
choco install rufus
choco install chocolatey-core.extension
choco install git.install
choco install googledrive
choco install malwarebytes
choco install obs-studio
choco install streamlabs-obs
choco install steam
choco install minecraft-launcher
choco install tabby
choco install alacritty
choco install cyberduck
choco install intellijidea-community
choco install pycharm-community
