taskkill /IM LeagueClient.exe /F
taskkill /IM LeagueCrashHandler64.exe /F
taskkill /IM LeagueClientUx.exe /F
taskkill /IM LeagueClientUxRender.exe /F
taskkill /IM vgc.exe /F
taskkill /IM RiotClientServices.exe /F
taskkill /IM RiotClientCrashHandler.exe /F
taskkill /IM VALORANT-Win64-Shipping.exe /F
taskkill /IM VALORANT.exe /F
